### ISSUE TITLE
Front matter doesn't parse correctly

### ISSUE THREAD

**Issue by lakruzz** [Praqma/ghreport#17]
when the readme contains underline first level header style:

```
Header
---
```

As opposed to hash levels:

```
# Header
```

see the phenomena in detail in praqma/noops#120

**Comment by lakruzz** [comment]
The regexp just needs to be non-greedy in https://github.com/Praqma/ghreport/blob/master/ghreport#L976

**Comment by ThaKangBaby** [comment]
@lakruzz Update from me and @JKrag:  The issue is not quite fixed yet.

The new regex fixes the problem with the broken frontmatter on git-phlow, but now fails to parse many others.

The diff of the latest run https://github.com/Praqma/repo-stat/commit/a266d4d161f8ac0d82bd395c73c5966c56d0ca2c
shows that quite a few repos now no longer show maintainer info etc.

@JKrag can look at the regex tomorrow if you don't fix it before then.

The concourse pipeline should now be running correctly and updating the report every 30 minutes.
